version: '3'
services:
  web:
    build: .

    volumes:
        - .:/code
    ports:
        - 8000:8000
    environment:
        - DB_HOST=db
        - DB_NAME=web
        - DB_USER=postgres
        - DB_PASSWORD=postgres

    depends_on:
        - db

  db:
    image: postgres
    volumes:
        - postgres_data:/var/lib/postgresql/data/
    environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_HOST=db

  rabbitmq:
    image: rabbitmq
    env_file:
      - .env
    ports:
      - "5672:5672"
    restart: on-failure
    command: >
      bash -c "celery -A config worker -l info --autoscale=5,1 && celery -A config beat"
  celery_worker:
    build: .
    command: bash -c "celery -A config worker -l info --autoscale=5,1"
    env_file:
      - .env
    volumes:
      - .:/cloudy
    restart: unless-stopped
    depends_on:
      - web
      - rabbitmq
  celery_beat:
    build: .
    command: "celery -A config beat"
    env_file:
      - .env
    volumes:
      - .:/cloudy
    depends_on:
      - web
      - rabbitmq
volumes:
   postgres_data: