version: '3'
services:
  web:
    build: .

    volumes:
        - .:/code
    ports:
        - 8000:8000
    env_file:
      - .env

    depends_on:
        - db

  db:
    image: postgres
    volumes:
        - postgres_data:/var/lib/postgresql/data/

    env_file:
      - .env

  rabbitmq:
    image: rabbitmq
    env_file:
      - .env
    ports:
      - "5672:5672"
    restart: on-failure
  celery_worker:
    build: .
    command: bash -c "celery -A config worker -l info --autoscale=5,1"
    env_file:
      - .env
    volumes:
      - .:/cloudy
    restart: unless-stopped
    depends_on:
      - web
      - rabbitmq
  celery_beat:
    build: .
    command: "celery -A config beat"
    env_file:
      - .env
    volumes:
      - .:/cloudy
    depends_on:
      - web
      - rabbitmq
volumes:
   postgres_data: