# Generated by Django 3.2.7 on 2021-09-25 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecast',
            name='taken_time',
        ),
    ]
