# Generated by Django 3.2.7 on 2021-09-25 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_forecast_taken_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecast',
            name='updated_on',
        ),
    ]
